### ISSUE TITLE
[EPIC] Setup dbt-common 

### ISSUE THREAD

**Issue by colin-rogers-dbt** [dbt-labs/dbt-common#4]
```[tasklist]
### Setup
- [ ] https://github.com/dbt-labs/dbt-common/issues/10
- [ ] https://github.com/dbt-labs/dbt-core/issues/9357
- [ ] https://github.com/dbt-labs/dbt-common/issues/12
- [ ] https://github.com/dbt-labs/dbt-adapter/issues/3
- [ ] https://github.com/dbt-labs/dbt-common/issues/16
- [ ] https://github.com/dbt-labs/dbt-common/issues/8
- [ ] https://github.com/dbt-labs/dbt-common/issues/18
- [ ] https://github.com/dbt-labs/dbt-common/issues/20
- [ ] https://github.com/dbt-labs/dbt-common/issues/14
- [ ] https://github.com/dbt-labs/dbt-common/issues/9
- [ ] https://github.com/dbt-labs/dbt-common/issues/24
- [ ] #41
```

```[tasklist]
### Build/Release
- [ ] https://github.com/dbt-labs/dbt-common/issues/5
- [ ] https://github.com/dbt-labs/dbt-common/issues/17
- [ ] https://github.com/dbt-labs/dbt-common/issues/6
- [ ] https://github.com/dbt-labs/dbt-common/issues/7
- [ ] https://github.com/dbt-labs/dbt-common/issues/30
```

```[tasklist]
### Follow on Cleanup
- [ ]
- [ ] https://github.com/dbt-labs/dbt-core/issues/9359
- [ ] https://github.com/dbt-labs/dbt-core/issues/8027
```
